import { LyricsList } from "@/types/lyrics";

export const lyrics: LyricsList = {
    'Warriors': [
        { time: 6, text: "As a child, you would wait and watch from far away" },
        { time: 11.8, text: "But you always knew that you'd be the one" },
        { time: 15, text: "That work while they all play" },
        { time: 18, text: "In youth, you'd lay awake at night and scheme" },
        { time: 24.4, text: "Of all the things that you would change" },
        { time: 27.7, text: "But it was just a dream" },
        { time: 30.8, text: "Here we are don't, turn away now (don't turn away)" },
        { time: 37, text: "We are the warriors that built this town" },
        { time: 43, text: "Here we are don't, turn away now (don't turn away)" },
        { time: 49.4, text: "We are the warriors that built this town" },
        { time: 55, text: "From dust" },
        { time: 56.5, text: 'Will come' },
        { time: 58.5, text: 'When you have to rise' },
        { time: 61.2, text: 'Above the best and prove yourself' },
        { time: 64.2, text: 'Your spirit never dies' },
        { time: 67.5, text: 'Farewell, I\'ve gone to take my throne above' },
        { time: 73.1, text: 'But don\'t weep for me' },
        { time: 75, text: 'Cause this will be the labor of my love' },
        { time: 80, text: "Here we are don't, turn away now (don't turn away)" },
        { time: 86, text: "We are the warriors that built this town" },
        { time: 92.5, text: "Here we are don't, turn away now (don't turn away)" },
        { time: 98, text: "We are the warriors that built this town" },
        { time: 104.5, text: "From dust" },
        { time: 108, text: '🎵' },
        { time: 116, text: '🎵' },
        { time: 129, text: "Here we are don't, turn away now (don't turn away)" },
        { time: 135, text: "We are the warriors that built this town" },
        { time: 142, text: "Here we are don't, turn away now (don't turn away)" },
        { time: 147.5, text: "We are the warriors that built this town" },
        { time: 153.5, text: "From dust" },
        { time: 155, text: '🎵' },
    ],
    '2002':[
        {time: 2.5, text: "I will always remember"},
        {time: 6, text: "The day you kissed my lips"},
        {time: 8, text: "Light as a feather"},
        {time: 11.25, text: "And it went just like this"},
        {time: 12.25, text: "No, it's never been better"},
        {time: 15, text: "Than the summer"},
        {time: 17, text: "of 2002"},
        {time: 20.5, text: "(ooh)"},
        {time: 22.5, text: "We were only eleven"},
        {time: 26.3, text: "But acting like grownups"},
        {time: 28, text: "Like we are in the present"},
        {time: 31, text: "Drinking from plastic cups"},
        {time: 33, text: "Singing love is forever"},
        {time: 35, text: "and ever"},
        {time: 37.5, text: "Well, I guess that was true"},
        {time: 40.5, text: "(ooh)"},
        {time: 43, text: "Dancing on the hood, In the middle of the woods"},
        {time: 46, text: "On an old Mustang, where we sang"},
        {time: 49, text: "Songs with all our childhood friends"},
        {time: 52.25, text: "And it went like this, say"},
        {time: 54, text: "Oops, I got 99 problems singing bye, bye, bye"},
        {time: 58, text: "Hold up, if you wanna go and take a ride with me"},
        {time: 61, text: "Better hit me, baby, one more time"},
        {time: 64, text: "Paint a picture for you and me"},
        {time: 66.5, text: "On the days when we were young"},
        {time: 69, text: "Singing at the top of both our lungs"},
        {time: 73, text: "Now we're under the covers"},
        {time: 76, text: "Fast forward to eighteen"},
        {time: 78, text: "We are more than lovers"},
        {time: 81, text: "Yeah, we are all we need"},
        {time: 83, text: "When we're holding each other"},
        {time: 85, text: "I'm taken back to 2002"},
        {time: 91, text: "(ooh)"},
        {time: 93, text: "(yeah)"},
        {time: 94, text: "Dancing on the hood, In the middle of the woods"},
        {time: 96, text: "On an old Mustang, where we sang"},
        {time: 99, text: "Songs with all our childhood friends"},
        {time: 102.5, text: "And it went like this, say"},
        {time: 104, text: "Oops, I got 99 problems singing bye, bye, bye"},
        {time: 108.5, text: "Hold up, if you wanna go and take a ride with me"},
        {time: 111, text: "Better hit me, baby, one more time"},
        {time: 114, text: "Paint a picture for you and me"},
        {time: 116.25, text: "On the days when we were young"},
        {time: 119, text: "Singing at the top of both our lungs"},
        {time: 122, text: "On the day we fell in love"},
        {time: 124.5, text: "(ooh-ooh)"},
        {time: 128.5, text: "On the day we fell in love"},
        {time: 129.5, text: "(ooh-ooh)"},
        {time: 134, text: "Dancing on the hood, in the middle of the woods"},
        {time: 136.5, text: "On an old Mustang, where we sang"},
        {time: 139, text: "Songs with all our childhood friends"},
        {time: 142.5, text: "Oh, now"},
        {time: 144, text: "Oops, I got 99 problems singing bye, bye, bye"},
        {time: 148, text: "Hold up, if you wanna go and take a ride with me"},
        {time: 151, text: "Better hit me, baby, one more time"},
        {time: 154, text: "Paint a picture for you and me"},
        {time: 156.5, text: "On the days when we were young"},
        {time: 159, text: "Singing at the top of both our lungs"},
        {time: 162.5, text: "On the day we fell in love"},
        {time: 164.5, text: "(ooh-ooh)"},
        {time: 168.5, text: "On the day we fell in love"},
        {time: 169.75, text: "(ooh-ooh)"},
        {time: 172.5, text: "On the day we fell in love"},
        {time: 174.5, text: "(ooh-ooh)"},
        {time: 177.5, text: "On the day we fell in love"},
        {time: 180.5, text: "(ooh-ooh)"},
        {time: 183, text:"On the day we fell in love, love, love"},

    ]
};