import { LyricsList } from "@/types/lyrics";

export const lyrics: LyricsList = {
    'Warriors': [
        { time: 6, text: "As a child, you would wait and watch from far away" },
        { time: 11.8, text: "But you always knew that you'd be the one" },
        { time: 15, text: "That work while they all play" },
        { time: 18, text: "In youth, you'd lay awake at night and scheme" },
        { time: 24.4, text: "Of all the things that you would change" },
        { time: 27.7, text: "But it was just a dream" },
        { time: 30.8, text: "Here we are don't, turn away now (don't turn away)" },
        { time: 37, text: "We are the warriors that built this town" },
        { time: 43, text: "Here we are don't, turn away now (don't turn away)" },
        { time: 49.4, text: "We are the warriors that built this town" },
        { time: 55, text: "From dust" },
        { time: 56.5, text: 'Will come' },
        { time: 58.5, text: 'When you have to rise' },
        { time: 61.2, text: 'Above the best and prove yourself' },
        { time: 64.2, text: 'Your spirit never dies' },
        { time: 67.5, text: 'Farewell, I\'ve gone to take my throne above' },
        { time: 73.1, text: 'But don\'t weep for me' },
        { time: 75, text: 'Cause this will be the labor of my love' },
        { time: 80, text: "Here we are don't, turn away now (don't turn away)" },
        { time: 86, text: "We are the warriors that built this town" },
        { time: 92.5, text: "Here we are don't, turn away now (don't turn away)" },
        { time: 98, text: "We are the warriors that built this town" },
        { time: 104.5, text: "From dust" },
        { time: 108, text: '🎵' },
        { time: 116, text: '🎵' },
        { time: 129, text: "Here we are don't, turn away now (don't turn away)" },
        { time: 135, text: "We are the warriors that built this town" },
        { time: 142, text: "Here we are don't, turn away now (don't turn away)" },
        { time: 147.5, text: "We are the warriors that built this town" },
        { time: 153.5, text: "From dust" },
        { time: 155, text: '🎵' },
    ],
};