import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "../styles/globals.scss";
import ModalRouter from "@/components/Modal/router";
import { SocketProvider } from "@/context/socket";

const NotoSansKR = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "ENO - 노래방에 피트니스를 더하다",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={NotoSansKR.className}>
				<SocketProvider>
					{children}
					<ModalRouter />
				</SocketProvider>
			</body>
		</html>
	);
}
